spring.datasource.url=jdbc:postgresql://localhost:5432/amalinki_test
spring.datasource.username=postgres
spring.datasource.password=12345

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.cors.allowed-origins=http://localhost:4200
