spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/amazonka_db
spring.datasource.username=postgres
spring.datasource.password=CHANGE_ME

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS}
app.auth.cookie.secure=${APP_AUTH_COOKIE_SECURE:true}
