spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/amazonka_db
spring.datasource.username=postgres
spring.datasource.password=CHANGE_ME

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

app.cors.allowed-origins=http://[167.233.102.40]
