spring.profiles.active=dev

spring.jpa.hibernate.ddl-auto=none

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB

jwt.secret=PolskaAmazonkaJwtSecretKey2026MustBeAtLeast256BitsLongForHS256Algorithm
jwt.expiration-ms=86400000

link.validation.max-links-per-run=25
link.validation.delay-ms-between-checks=2000
link.validation.min-hours-between-checks=24
